In [1]:
import gym

In [8]:
env = gym.make('CartPole-v0')

In [19]:
env.reset()

array([0.01113674, 0.02793681, 0.04001134, 0.03653143], dtype=float32)

In [20]:
for _ in range(1000):
    env.render()
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    print(observation)

[ 0.01169548  0.22246283  0.04074197 -0.24326387]
[ 0.01614474  0.41697988  0.0358767  -0.5228225 ]
[ 0.02448433  0.22137181  0.02542024 -0.21905373]
[0.02891177 0.02589589 0.02103917 0.08153819]
[ 0.02942969 -0.16952124  0.02266993  0.38078406]
[ 0.02603926 -0.36495766  0.03028561  0.68052775]
[ 0.01874011 -0.56048685  0.04389617  0.98258966]
[ 0.00753037 -0.36597973  0.06354796  0.7040113 ]
[ 2.1077906e-04 -5.6192207e-01  7.7628188e-02  1.0160021e+00]
[-0.01102766 -0.36791623  0.09794823  0.7486695 ]
[-0.01838599 -0.5642431   0.11292163  1.0704991 ]
[-0.02967085 -0.37078062  0.1343316   0.815282  ]
[-0.03708646 -0.1777286   0.15063724  0.5676876 ]
[-0.04064103 -0.37460676  0.161991    0.9037806 ]
[-0.04813317 -0.18200563  0.1800666   0.6660785 ]
[-0.05177328 -0.37911442  0.19338818  1.0096153 ]
[-0.05935557 -0.5762174   0.21358047  1.3562608 ]
[-0.07087991 -0.7732819   0.2407057   1.7074574 ]
[-0.08634555 -0.9702271   0.27485484  2.0644445 ]
[-0.1057501  -0.77875495  0.31614372  1.86

C:\Users\82514\anaconda3\lib\site-packages\gym\logger.py:34: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))


[-0.17659485 -0.60349387  0.51417994  2.1917462 ]
[-0.18866473 -0.41553506  0.55801487  2.090859  ]
[-0.19697544 -0.610834    0.59983206  2.4950433 ]
[-0.20919211 -0.8046899   0.6497329   2.9010293 ]
[-0.22528592 -0.99661326  0.7077535   3.3081188 ]
[-0.24521817 -1.1860206   0.7739159   3.715131  ]
[-0.2689386 -0.9954673  0.8482185  3.7162   ]
[-0.28884792 -0.805187    0.92254245  3.747976  ]
[-0.30495167 -0.61489093  0.997502    3.8099852 ]
[-0.3172495 -0.4242518  1.0737017  3.9018753]
[-0.32573453 -0.60226613  1.1517392   4.2876287 ]
[-0.33777985 -0.40795514  1.2374917   4.437592  ]
[-0.34593895 -0.57823074  1.3262436   4.798975  ]
[-0.35750356 -0.74353546  1.4222231   5.1442633 ]
[-0.37237427 -0.90375674  1.5251083   5.4706    ]
[-0.3904494 -1.0590284  1.6345204  5.7749305]
[-0.41162997 -1.2097825   1.750019    6.0539336 ]
[-0.43582562 -0.99236447  1.8710977   6.4013615 ]
[-0.45567292 -1.1356764   1.9991249   6.618615  ]
[-0.47838646 -1.2778921   2.1314971   6.797451  ]
[-0.5039443 

[-5.0119624 -1.233647  14.7419195  8.402739 ]
[-5.0366354 -0.9873466 14.909974   8.85465  ]
[-5.056382  -1.1157202 15.087068   8.930704 ]
[-5.0786967 -0.8745171 15.265681   9.39602  ]
[-5.096187  -0.6401247 15.453602   9.83961  ]
[-5.1089892  -0.80721205 15.650394    9.671022  ]
[-5.1251335 -0.6060649 15.843815   9.989159 ]
[-5.1372547  -0.81601393 16.043598    9.63732   ]
[-5.1535754  -0.65646344 16.236343    9.766457  ]
[-5.1667047  -0.51709086 16.431673    9.798789  ]
[-5.1770463 -0.7731424 16.62765    9.316301 ]
[-5.192509   -0.65763414 16.813974    9.18746   ]
[-5.205662  -0.9169547 16.997725   8.750295 ]
[-5.224001  -0.8049865 17.17273    8.514411 ]
[-5.240101  -1.0539358 17.343018   8.182542 ]
[-5.2611794 -0.9319685 17.50667    7.8774004]
[-5.2798185 -1.1666155 17.664217   7.670528 ]
[-5.303151  -1.0283726 17.817627   7.320134 ]
[-5.3237185 -1.2500958 17.964031   7.2384677]
[-5.3487206 -1.0943552 18.108799   6.862991 ]
[-5.3706074 -0.9286243 18.24606    6.481132 ]
[-5.38918   -1

[-6.7599926  0.5958324 36.104465   5.510054 ]
[-6.748076   0.7497452 36.21467    5.221643 ]
[-6.733081    0.54427654 36.3191      4.9553194 ]
[-6.7221956  0.342534  36.41821    4.7240386]
[-6.715345    0.14382815 36.512688    4.5275054 ]
[-6.712468   -0.05250191 36.603237    4.3653865 ]
[-6.713518    0.12182923 36.690544    3.9843497 ]
[-6.7110815  -0.06988657 36.770233    3.8889039 ]
[-6.7124796  -0.26097882 36.84801     3.8250444 ]
[-6.717699   -0.07709128 36.92451     3.4221387 ]
[-6.7192407   0.11049379 36.992954    3.0154054 ]
[-6.717031   -0.07751103 37.053265    3.039193  ]
[-6.718581    0.11400402 37.114048    2.6328282 ]
[-6.716301    0.30767217 37.166702    2.228281  ]
[-6.7101474   0.11990368 37.21127     2.321712  ]
[-6.7077494  -0.06871311 37.2577      2.4338286 ]
[-6.7091236   0.12686768 37.30638     2.042976  ]
[-6.7065864  0.3233958 37.34724    1.6581093]
[-6.7001185  0.52052   37.3804     1.279211 ]
[-6.689708    0.33053014 37.405987    1.4577214 ]
[-6.6830974   0.1399

[-5.0657544 -1.4041332 54.029922   9.724214 ]
[-5.0938373 -1.2728906 54.224407   9.712606 ]
[-5.119295  -1.1565741 54.41866    9.617556 ]
[-5.1424265 -1.0500001 54.611008   9.45315  ]
[-5.1634264 -1.3144448 54.80007    9.036433 ]
[-5.1897154 -1.207789  54.9808     8.775364 ]
[-5.213871  -1.0959376 55.156307   8.480873 ]
[-5.23579   -1.3402947 55.325924   8.256598 ]
[-5.2625957 -1.2114278 55.49106    7.914298 ]
[-5.286824  -1.4409086 55.64934    7.827167 ]
[-5.3156424 -1.6657554 55.805885   7.806821 ]
[-5.3489575 -1.5089521 55.96202    7.4347277]
[-5.3791366 -1.3408405 56.110718   7.061972 ]
[-5.4059534 -1.1631823 56.251957   6.695955 ]
[-5.4292173 -1.3658161 56.385876   6.900665 ]
[-5.4565334 -1.5657896 56.523888   7.1490097]
[-5.487849  -1.7617829 56.66687    7.435625 ]
[-5.523085  -1.9520297 56.815582   7.7536745]
[-5.5621257 -1.7461344 56.970654   7.5333123]
[-5.5970483 -1.9217823 57.121323   7.8940864]
[-5.6354837 -2.0869436 57.2792     8.261613 ]
[-5.6772227 -1.8618495 57.444435  

[-14.492517  -3.508672  84.0542     9.3961  ]
[-14.562691   -3.6323655  84.24212     9.467155 ]
[-14.635338   -3.3880632  84.431465    9.934838 ]
[-14.703099  -3.153634  84.63016   10.372065]
[-14.766171  -2.936284  84.8376    10.748391]
[-14.824898   -3.1332579  85.05257    10.448669 ]
[-14.887563   -3.3549552  85.26154    10.057946 ]
[-14.954661   -3.2091775  85.4627     10.131083 ]
[-15.018846   -3.0839653  85.66532    10.106259 ]
[-15.080524   -3.3497381  85.86745     9.621479 ]
[-15.147519   -3.6146867  86.059875    9.167616 ]
[-15.219813   -3.8747318  86.24323     8.762011 ]
[-15.297308  -3.763729  86.41847    8.496312]
[-15.372582   -3.6471813  86.588394    8.198089 ]
[-15.445526   -3.5224555  86.75236     7.87346  ]
[-15.515975   -3.7546031  86.90983     7.720358 ]
[-15.591067   -3.6118088  87.06423     7.3589525]
[-15.663303   -3.8314779  87.21142     7.333319 ]
[-15.739933   -3.6705918  87.35808     6.9561806]
[-15.813345   -3.880906   87.49721     7.0478024]
[-15.890963   -3

[-24.477226   -1.4716315 115.51622    10.28036  ]
[-24.506659   -1.2095859 115.72183    10.769626 ]
[-24.53085    -1.3402684 115.937225   10.744573 ]
[-24.557655   -1.4968418 116.152115   10.607682 ]
[-24.587591   -1.6811053 116.364265   10.357819 ]
[-24.621214   -1.8908509 116.57143    10.008915 ]
[-24.65903   -1.733283 116.77161   10.136359]
[-24.693697   -1.5978957 116.97433    10.161999 ]
[-24.725655   -1.4813374 117.17757    10.094412 ]
[-24.755281   -1.3781666 117.379456    9.9486685]
[-24.782845   -1.6500531 117.57843     9.5113535]
[-24.815845   -1.5509133 117.76866     9.259273 ]
[-24.846865   -1.4475058 117.95384     8.971889 ]
[-24.875814   -1.7001984 118.133286    8.735374 ]
[-24.909819   -1.5792887 118.30799     8.398967 ]
[-24.941404   -1.4461192 118.47597     8.04525  ]
[-24.970325   -1.3002679 118.63687     7.6789103]
[-24.996332   -1.1422442 118.79045     7.30542  ]
[-25.019176   -1.3548898 118.93656     7.406864 ]
[-25.046274   -1.5646073 119.084694    7.5646663]
[-25

In [25]:
env.close()

In [2]:
from gym import envs

In [23]:
env_specs = envs.registry.all()
envs_ids = [env_spec.id for env_spec in env_specs]

In [24]:
envs_ids

['CartPole-v0',
 'CartPole-v1',
 'MountainCar-v0',
 'MountainCarContinuous-v0',
 'Pendulum-v0',
 'Acrobot-v1',
 'LunarLander-v2',
 'LunarLanderContinuous-v2',
 'BipedalWalker-v3',
 'BipedalWalkerHardcore-v3',
 'CarRacing-v0',
 'Blackjack-v1',
 'FrozenLake-v1',
 'FrozenLake8x8-v1',
 'CliffWalking-v0',
 'Taxi-v3',
 'Reacher-v2',
 'Pusher-v2',
 'Thrower-v2',
 'Striker-v2',
 'InvertedPendulum-v2',
 'InvertedDoublePendulum-v2',
 'HalfCheetah-v2',
 'HalfCheetah-v3',
 'Hopper-v2',
 'Hopper-v3',
 'Swimmer-v2',
 'Swimmer-v3',
 'Walker2d-v2',
 'Walker2d-v3',
 'Ant-v2',
 'Ant-v3',
 'Humanoid-v2',
 'Humanoid-v3',
 'HumanoidStandup-v2',
 'FetchSlide-v1',
 'FetchPickAndPlace-v1',
 'FetchReach-v1',
 'FetchPush-v1',
 'HandReach-v0',
 'HandManipulateBlockRotateZ-v0',
 'HandManipulateBlockRotateZTouchSensors-v0',
 'HandManipulateBlockRotateZTouchSensors-v1',
 'HandManipulateBlockRotateParallel-v0',
 'HandManipulateBlockRotateParallelTouchSensors-v0',
 'HandManipulateBlockRotateParallelTouchSensors-v1',


# MountainCar-v0

In [2]:
env = gym.make('MountainCar-v0')

In [3]:
env.observation_space   # 观测空间

Box([-1.2  -0.07], [0.6  0.07], (2,), float32)

In [4]:
env.action_space   # 动作空间

Discrete(3)

In [5]:
(env.observation_space.low, env.observation_space.high)   # 观测范围

(array([-1.2 , -0.07], dtype=float32), array([0.6 , 0.07], dtype=float32))

In [6]:
env.action_space.n    # 动作数

3

In [7]:
class BespokeAgent:
    
    def __init__(self, env):
        pass
    
    def decide(self, observation):
        position, velocity = observation
        lb = min(-0.09 * (position + 0.25) ** 2 + 0.03, 0.3 * (position + 0.9) ** 4 - 0.008)
        ub = -0.07 * (position + 0.38) ** 2 + 0.07
        
        if lb < velocity < ub:
            action = 2
        else:
            action = 0
        
        return action
    
    def learn(self, *args):
        pass

In [8]:
agent = BespokeAgent(env)

In [9]:
def play_montecarlo(env, agent, render=False, train=False):
    episode_reward = 0. # 回合总奖励
    observation = env.reset()  
    while True:
        if render:
            env.render()
        action = agent.decide(observation)
        next_observation, reward, done, _ = env.step(action)  # 执行动作
        episode_reward += reward
        if train:
            agent.learn(observation, action, reward, done)
        if done:
            break
        observation = next_observation
    return episode_reward

In [10]:
env.seed(0)
episode_reward = play_montecarlo(env, agent, render=True)
print('回合奖励 = {}'.format(episode_reward))

回合奖励 = -105.0


In [11]:
env.close()

In [12]:
import numpy as np

In [13]:
episode_rewards = [play_montecarlo(env, agent) for _ in range(100)]
print('平均回合奖励 = {}'.format(np.mean(episode_rewards)))

平均回合奖励 = -102.61


In [17]:
w = 3.4
t0 = 2

In [22]:
print('{:.1f}'.format(w))

3.4
